---
- name: Update kernel and reboot if required (Ubuntu/Debian)
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages including kernel
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists

    - name: Wait for host to come back
      wait_for_connection:
        timeout: 300
