---
- name: Reboot system if kernel update requires it
  hosts: all
  become: true
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system
      reboot:
        reboot_timeout: 600
        test_command: whoami
      when: reboot_required.stat.exists

    - name: Wait for system to be up
      wait_for_connection:
        timeout: 300